server:
  port: 8080
  pprof_port: 6060 # Port for Continuous Profiling (0 - disabled)
  debug: false
  cors_allowed_origins:
    - http://localhost:8080 # Leave empty to disable CORS
  record_retention_days: 7
  gc_percent: 50
  gc_memory_limit_mb: 2048
  hls:
    live_segments_in_memory: 3 # Number of TS segments retained in RAM (3 for High-Density 600+ cams, 5 for high latency networks)
  grpc:
    address: "0.0.0.0"
    port: 50051
  tls:
    cert_file: "" # Path to TLS certificate (optional)
    key_file: ""  # Path to TLS key (optional)
  webrtc:
    ice_servers:
      - "stun:stun.l.google.com:19302"
    ice_transport_policy: "all" # 'all' or 'relay'
    turn_username: ""
    turn_password: ""

auth:
  secret: "" # Leave empty for auto-generation
  # secret: "your-jwt-secret-here" # The secret is generated automatically on first run of ruseon-core

global_tags:
  - id: "indoor"
    name: "Внутри помещения"
    color: "#28a745"
  - id: "outdoor"
    name: "На улице"
    color: "#dc3545"

cameras:
  - id: "cam-01"
    url: "rtsp://username:password@192.168.1.100:554/stream1"
    record: true
    retention_days: 14
    tags: ["outdoor"]
    folder_id: "main-building"
    comment: "Парковка"
    transport: "tcp"

# events:
#   webhooks:
#     - url: "https://my-vms.com/api/webhook"
#       topics: ["camera_offline", "archive_segment_ready"]
#       secret: "super-secret-hmac-key"
#   mqtt:
#     enabled: true
#     url: "mqtt://mqtt.eclipseprojects.io:1883"
#     username: "" # Leave empty to disable authentication
#     password: "" # Leave empty to disable authentication



