package backup

import (
	"context"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/RUSEGAL/ruseon-core/v2/pkg/config"
	"github.com/RUSEGAL/ruseon-core/v2/pkg/storage"
)

func TestWorker_DoBackupAndCleanup(t *testing.T) {
	tempDir := t.TempDir()
	dbDir := filepath.Join(tempDir, "db")
	backupDir := filepath.Join(tempDir, "backups")

	store, err := storage.NewStorage(dbDir)
	if err != nil {
		t.Fatalf("failed to create storage: %v", err)
	}
	defer store.Close()

	// Save some data
	_ = store.SaveCamera(&config.CameraConfig{ID: "cam1"})

	w := NewWorker(store, backupDir, 1*time.Hour, 1) // 1 day retention

	// Create an artificially old backup file to test cleanup
	oldBackupPath := filepath.Join(backupDir, "old.bak")
	f, err := os.Create(oldBackupPath)
	if err != nil {
		t.Fatalf("failed to create old backup: %v", err)
	}
	f.Close()

	twoDaysAgo := time.Now().Add(-48 * time.Hour)
	if err := os.Chtimes(oldBackupPath, twoDaysAgo, twoDaysAgo); err != nil {
		t.Fatalf("failed to change time of old backup: %v", err)
	}

	// Create a new backup file to ensure it doesn't get cleaned up
	newBackupPath := filepath.Join(backupDir, "new.bak")
	f2, _ := os.Create(newBackupPath)
	f2.Close()

	// Run backup manually
	w.doBackup()

	// Check files
	entries, err := os.ReadDir(backupDir)
	if err != nil {
		t.Fatalf("failed to read backup dir: %v", err)
	}

	// We should have 'new.bak' and the one generated by doBackup(), but 'old.bak' should be deleted.
	foundOld := false
	foundNew := false
	foundGenerated := false

	for _, entry := range entries {
		switch entry.Name() {
		case "old.bak":
			foundOld = true
		case "new.bak":
			foundNew = true
		default:
			foundGenerated = true
		}
	}

	if foundOld {
		t.Errorf("expected old.bak to be deleted")
	}
	if !foundNew {
		t.Errorf("expected new.bak to be kept")
	}
	if !foundGenerated {
		t.Errorf("expected generated backup to exist")
	}
}

func TestWorker_RunLifecycle(t *testing.T) {
	tempDir := t.TempDir()
	dbDir := filepath.Join(tempDir, "db")
	backupDir := filepath.Join(tempDir, "backups")

	store, _ := storage.NewStorage(dbDir)
	defer store.Close()

	// Use very short interval
	w := NewWorker(store, backupDir, 10*time.Millisecond, 1)

	ctx, cancel := context.WithCancel(context.Background())
	
	done := make(chan struct{})
	// Start in background
	go func() {
		w.Run(ctx)
		close(done)
	}()
	
	// Wait a bit to let it tick
	time.Sleep(50 * time.Millisecond)
	
	cancel()
	<-done // Wait for Run to exit before closing store
	
	// Ensure at least one backup was created via ticker
	entries, _ := os.ReadDir(backupDir)
	if len(entries) == 0 {
		t.Errorf("expected at least one backup file created by ticker, got 0")
	}
}
