// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: api/proto/frame.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CameraId      string                 `protobuf:"bytes,1,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_api_proto_frame_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_frame_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_frame_proto_rawDescGZIP(), []int{0}
}

func (x *StreamRequest) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

type FrameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Codec         string                 `protobuf:"bytes,1,opt,name=codec,proto3" json:"codec,omitempty"`                              // Например, "H264" или "H265"
	IsKeyframe    bool                   `protobuf:"varint,2,opt,name=is_keyframe,json=isKeyframe,proto3" json:"is_keyframe,omitempty"` // true если это I-Frame (ключевой кадр)
	Pts           int64                  `protobuf:"varint,3,opt,name=pts,proto3" json:"pts,omitempty"`                                 // Presentation Time Stamp (миллисекунды)
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`                          // Сырые байты кадра (NAL-юниты)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameResponse) Reset() {
	*x = FrameResponse{}
	mi := &file_api_proto_frame_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameResponse) ProtoMessage() {}

func (x *FrameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_frame_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameResponse.ProtoReflect.Descriptor instead.
func (*FrameResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_frame_proto_rawDescGZIP(), []int{1}
}

func (x *FrameResponse) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

func (x *FrameResponse) GetIsKeyframe() bool {
	if x != nil {
		return x.IsKeyframe
	}
	return false
}

func (x *FrameResponse) GetPts() int64 {
	if x != nil {
		return x.Pts
	}
	return 0
}

func (x *FrameResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_api_proto_frame_proto protoreflect.FileDescriptor

const file_api_proto_frame_proto_rawDesc = "" +
	"\n" +
	"\x15api/proto/frame.proto\x12\x11ruseon.core.frame\",\n" +
	"\rStreamRequest\x12\x1b\n" +
	"\tcamera_id\x18\x01 \x01(\tR\bcameraId\"r\n" +
	"\rFrameResponse\x12\x14\n" +
	"\x05codec\x18\x01 \x01(\tR\x05codec\x12\x1f\n" +
	"\vis_keyframe\x18\x02 \x01(\bR\n" +
	"isKeyframe\x12\x10\n" +
	"\x03pts\x18\x03 \x01(\x03R\x03pts\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload2f\n" +
	"\fFrameService\x12V\n" +
	"\fStreamFrames\x12 .ruseon.core.frame.StreamRequest\x1a .ruseon.core.frame.FrameResponse\"\x000\x01B2Z0github.com/RUSEGAL/ruseon-core/pkg/grpc/pbb\x06proto3"

var (
	file_api_proto_frame_proto_rawDescOnce sync.Once
	file_api_proto_frame_proto_rawDescData []byte
)

func file_api_proto_frame_proto_rawDescGZIP() []byte {
	file_api_proto_frame_proto_rawDescOnce.Do(func() {
		file_api_proto_frame_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_frame_proto_rawDesc), len(file_api_proto_frame_proto_rawDesc)))
	})
	return file_api_proto_frame_proto_rawDescData
}

var file_api_proto_frame_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_frame_proto_goTypes = []any{
	(*StreamRequest)(nil), // 0: ruseon.core.frame.StreamRequest
	(*FrameResponse)(nil), // 1: ruseon.core.frame.FrameResponse
}
var file_api_proto_frame_proto_depIdxs = []int32{
	0, // 0: ruseon.core.frame.FrameService.StreamFrames:input_type -> ruseon.core.frame.StreamRequest
	1, // 1: ruseon.core.frame.FrameService.StreamFrames:output_type -> ruseon.core.frame.FrameResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_frame_proto_init() }
func file_api_proto_frame_proto_init() {
	if File_api_proto_frame_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_frame_proto_rawDesc), len(file_api_proto_frame_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_frame_proto_goTypes,
		DependencyIndexes: file_api_proto_frame_proto_depIdxs,
		MessageInfos:      file_api_proto_frame_proto_msgTypes,
	}.Build()
	File_api_proto_frame_proto = out.File
	file_api_proto_frame_proto_goTypes = nil
	file_api_proto_frame_proto_depIdxs = nil
}
