// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.31.1
// source: api/proto/frame.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BoundingBox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`                   // Координата X левого верхнего угла (0.0 - 1.0)
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`                   // Координата Y левого верхнего угла (0.0 - 1.0)
	Width         float32                `protobuf:"fixed32,3,opt,name=width,proto3" json:"width,omitempty"`           // Ширина рамки (0.0 - 1.0)
	Height        float32                `protobuf:"fixed32,4,opt,name=height,proto3" json:"height,omitempty"`         // Высота рамки (0.0 - 1.0)
	Label         string                 `protobuf:"bytes,5,opt,name=label,proto3" json:"label,omitempty"`             // Имя класса (например, "person")
	Confidence    float32                `protobuf:"fixed32,6,opt,name=confidence,proto3" json:"confidence,omitempty"` // Уверенность детекции (0.0 - 1.0)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoundingBox) Reset() {
	*x = BoundingBox{}
	mi := &file_api_proto_frame_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoundingBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundingBox) ProtoMessage() {}

func (x *BoundingBox) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_frame_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundingBox.ProtoReflect.Descriptor instead.
func (*BoundingBox) Descriptor() ([]byte, []int) {
	return file_api_proto_frame_proto_rawDescGZIP(), []int{0}
}

func (x *BoundingBox) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *BoundingBox) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *BoundingBox) GetWidth() float32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *BoundingBox) GetHeight() float32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *BoundingBox) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *BoundingBox) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type MetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CameraId      string                 `protobuf:"bytes,1,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	Pts           int64                  `protobuf:"varint,2,opt,name=pts,proto3" json:"pts,omitempty"`        // PTS кадра, к которому относятся метаданные
	Objects       []*BoundingBox         `protobuf:"bytes,3,rep,name=objects,proto3" json:"objects,omitempty"` // Обнаруженные объекты
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataRequest) Reset() {
	*x = MetadataRequest{}
	mi := &file_api_proto_frame_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataRequest) ProtoMessage() {}

func (x *MetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_frame_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataRequest.ProtoReflect.Descriptor instead.
func (*MetadataRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_frame_proto_rawDescGZIP(), []int{1}
}

func (x *MetadataRequest) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

func (x *MetadataRequest) GetPts() int64 {
	if x != nil {
		return x.Pts
	}
	return 0
}

func (x *MetadataRequest) GetObjects() []*BoundingBox {
	if x != nil {
		return x.Objects
	}
	return nil
}

type MetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataResponse) Reset() {
	*x = MetadataResponse{}
	mi := &file_api_proto_frame_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataResponse) ProtoMessage() {}

func (x *MetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_frame_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataResponse.ProtoReflect.Descriptor instead.
func (*MetadataResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_frame_proto_rawDescGZIP(), []int{2}
}

func (x *MetadataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MetadataResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CameraId      string                 `protobuf:"bytes,1,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_api_proto_frame_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_frame_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_frame_proto_rawDescGZIP(), []int{3}
}

func (x *StreamRequest) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

type FrameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Codec         string                 `protobuf:"bytes,1,opt,name=codec,proto3" json:"codec,omitempty"`                              // Например, "H264" или "H265"
	IsKeyframe    bool                   `protobuf:"varint,2,opt,name=is_keyframe,json=isKeyframe,proto3" json:"is_keyframe,omitempty"` // true если это I-Frame (ключевой кадр)
	Pts           int64                  `protobuf:"varint,3,opt,name=pts,proto3" json:"pts,omitempty"`                                 // Presentation Time Stamp (миллисекунды)
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`                          // Сырые байты кадра (NAL-юниты)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameResponse) Reset() {
	*x = FrameResponse{}
	mi := &file_api_proto_frame_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameResponse) ProtoMessage() {}

func (x *FrameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_frame_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameResponse.ProtoReflect.Descriptor instead.
func (*FrameResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_frame_proto_rawDescGZIP(), []int{4}
}

func (x *FrameResponse) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

func (x *FrameResponse) GetIsKeyframe() bool {
	if x != nil {
		return x.IsKeyframe
	}
	return false
}

func (x *FrameResponse) GetPts() int64 {
	if x != nil {
		return x.Pts
	}
	return 0
}

func (x *FrameResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_api_proto_frame_proto protoreflect.FileDescriptor

const file_api_proto_frame_proto_rawDesc = "" +
	"\n" +
	"\x15api/proto/frame.proto\x12\x11ruseon.core.frame\"\x8d\x01\n" +
	"\vBoundingBox\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x02R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x02R\x06height\x12\x14\n" +
	"\x05label\x18\x05 \x01(\tR\x05label\x12\x1e\n" +
	"\n" +
	"confidence\x18\x06 \x01(\x02R\n" +
	"confidence\"z\n" +
	"\x0fMetadataRequest\x12\x1b\n" +
	"\tcamera_id\x18\x01 \x01(\tR\bcameraId\x12\x10\n" +
	"\x03pts\x18\x02 \x01(\x03R\x03pts\x128\n" +
	"\aobjects\x18\x03 \x03(\v2\x1e.ruseon.core.frame.BoundingBoxR\aobjects\"F\n" +
	"\x10MetadataResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\",\n" +
	"\rStreamRequest\x12\x1b\n" +
	"\tcamera_id\x18\x01 \x01(\tR\bcameraId\"r\n" +
	"\rFrameResponse\x12\x14\n" +
	"\x05codec\x18\x01 \x01(\tR\x05codec\x12\x1f\n" +
	"\vis_keyframe\x18\x02 \x01(\bR\n" +
	"isKeyframe\x12\x10\n" +
	"\x03pts\x18\x03 \x01(\x03R\x03pts\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload2\xc3\x01\n" +
	"\fFrameService\x12V\n" +
	"\fStreamFrames\x12 .ruseon.core.frame.StreamRequest\x1a .ruseon.core.frame.FrameResponse\"\x000\x01\x12[\n" +
	"\fPushMetadata\x12\".ruseon.core.frame.MetadataRequest\x1a#.ruseon.core.frame.MetadataResponse\"\x00(\x01B/Z-github.com/RUSEGAL/ruseon-core/v2/pkg/grpc/pbb\x06proto3"

var (
	file_api_proto_frame_proto_rawDescOnce sync.Once
	file_api_proto_frame_proto_rawDescData []byte
)

func file_api_proto_frame_proto_rawDescGZIP() []byte {
	file_api_proto_frame_proto_rawDescOnce.Do(func() {
		file_api_proto_frame_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_frame_proto_rawDesc), len(file_api_proto_frame_proto_rawDesc)))
	})
	return file_api_proto_frame_proto_rawDescData
}

var file_api_proto_frame_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_proto_frame_proto_goTypes = []any{
	(*BoundingBox)(nil),      // 0: ruseon.core.frame.BoundingBox
	(*MetadataRequest)(nil),  // 1: ruseon.core.frame.MetadataRequest
	(*MetadataResponse)(nil), // 2: ruseon.core.frame.MetadataResponse
	(*StreamRequest)(nil),    // 3: ruseon.core.frame.StreamRequest
	(*FrameResponse)(nil),    // 4: ruseon.core.frame.FrameResponse
}
var file_api_proto_frame_proto_depIdxs = []int32{
	0, // 0: ruseon.core.frame.MetadataRequest.objects:type_name -> ruseon.core.frame.BoundingBox
	3, // 1: ruseon.core.frame.FrameService.StreamFrames:input_type -> ruseon.core.frame.StreamRequest
	1, // 2: ruseon.core.frame.FrameService.PushMetadata:input_type -> ruseon.core.frame.MetadataRequest
	4, // 3: ruseon.core.frame.FrameService.StreamFrames:output_type -> ruseon.core.frame.FrameResponse
	2, // 4: ruseon.core.frame.FrameService.PushMetadata:output_type -> ruseon.core.frame.MetadataResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_frame_proto_init() }
func file_api_proto_frame_proto_init() {
	if File_api_proto_frame_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_frame_proto_rawDesc), len(file_api_proto_frame_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_frame_proto_goTypes,
		DependencyIndexes: file_api_proto_frame_proto_depIdxs,
		MessageInfos:      file_api_proto_frame_proto_msgTypes,
	}.Build()
	File_api_proto_frame_proto = out.File
	file_api_proto_frame_proto_goTypes = nil
	file_api_proto_frame_proto_depIdxs = nil
}
